update BOJ_17141
bcaitech1/team36-algorithm pull request #9
Opened 2021-02-25 13:36 UTC by hcworkplace

피드백 주세요~~~~

2021-02-26 13:18 UTC, gvsteve24 commented on Algorithm/solution/BOJ17141.py
> +    '''
```suggestion
    '''
    # 벽이 이중으로 있는 경우 탐색이 멈춥니다
    # 따라서 벽은 모두 0으로 초기화 하였습니다.
    for i in range(N):
        for j in range(N):
            if board[i][j] == '1':
                chk[i][j] = 0
```

2021-02-26 13:19 UTC, gvsteve24 commented on Algorithm/solution/BOJ17141.py
> +            if board[nx][ny] == '1': continue
```suggestion

```

2021-02-26 13:19 UTC, gvsteve24 commented on Algorithm/solution/BOJ17141.py
> +            if board[nx][ny] == '1': continue
위에서 벽을 표시하여서 벽 조건은 없어졌습니다.

2021-02-26 13:20 UTC, gvsteve24 commented on Algorithm/solution/BOJ17141.py
> +
```suggestion
def generate_min_array(pool: list):
    # this function compare each element of possible chk_list and select minimum value 
    # if one element is -1 (unreachable area), min value is the other element in between 
    # pool : list of possible virus spread simulation(chk_list)
    min_array = [[float('inf')]*N for _ in range(N)]
    for i in range(N):
        for j in range(N):
            for k, chk_list in enumerate(pool):
                if k != 0:
                    if min_array[i][j] != -1 and chk_list[i][j] != -1:
                        min_array[i][j] = min(min_array[i][j], chk_list[i][j])
                    elif min_array[i][j] != -1:
                        continue
                    elif chk_list[i][j] != -1:
                        min_array[i][j] = chk_list[i][j]
                    else:
                        min_array[i][j] = min(min_array[i][j], chk_list[i][j]) 

                min_array[i][j] = min(min_array[i][j], chk_list[i][j]) 

    return min_array
```

2021-02-26 13:20 UTC, gvsteve24 commented on Algorithm/solution/BOJ17141.py
> +N,M = map(int,input().split())
```suggestion
def is_all_infected(array):
    # this function checks if 2-dimensional array has element with value -1
    for i in range(len(array)):
        for j in range(len(array)):
            if array[i][j] == -1:
                return False
    return True
    
```

2021-02-26 13:21 UTC, gvsteve24 commented on Algorithm/solution/BOJ17141.py
> +    for j in i:
```suggestion
    for j in i:
        temp.append(bfs(board,list(j),N))
    
    if not is_all_infected(generate_min_array(temp)):               # 바이러스가 다 퍼지지 않았다면 후보가 될수 없습니다.
        continue 
    else:
        temp_result = max(map(max, generate_min_array(temp)))       # 시간이 표현된 2차행렬에서 최대값 뽑기
        res.append(temp_result)                                     # 뽑은 값 res에 추가

```

2021-02-26 13:22 UTC, gvsteve24 commented on Algorithm/solution/BOJ17141.py
> +        res.append(min(temp))
```suggestion
```

2021-02-26 13:23 UTC, gvsteve24 commented on Algorithm/solution/BOJ17141.py
> +        res.append(min(temp))
```suggestion
        for j in i:
        temp.append(bfs(board,list(j),N))
    
    if not is_all_infected(generate_min_array(temp)):               # 바이러스가 다 퍼지지 않았다면 후보가 될수 없습니다.
        continue 
    else:
        temp_result = max(map(max, generate_min_array(temp)))       # 시간이 표현된 2차행렬에서 최대값 뽑기
        res.append(temp_result)                                     # 뽑은 값 res에 추가

```

2021-02-26 13:24 UTC, gvsteve24 commented on Algorithm/solution/BOJ17141.py
> +        res.append(min(temp))
```suggestion
    for j in i:
        temp.append(bfs(board,list(j),N))
    
    if not is_all_infected(generate_min_array(temp)):               # 바이러스가 다 퍼지지 않았다면 후보가 될수 없습니다.
        continue 
    else:
        temp_result = max(map(max, generate_min_array(temp)))       # 시간이 표현된 2차행렬에서 최대값 뽑기
        res.append(temp_result)                                     # 뽑은 값 res에 추가

```

2021-02-26 13:24 UTC, gvsteve24 commented on Algorithm/solution/BOJ17141.py
> +print(min(res))
```suggestion
if len(res) != 0:                                                   # 가능한 경우가 있다면 그중에 가장 적게 걸린 시간 출력
    print(min(res)) 
else:                                                               # 다 퍼지는게 불가능하다면 -1 출력
    print(-1)
```

2021-02-26 13:25 UTC, gvsteve24 requested changes
백준에서 돌아가도록 수정하였습니다.
읽어보시고 코멘트 주세요~!

2021-03-02 08:20 UTC, hcworkplace commented
코드 한번에 확인하게 맨 처음 제 suggestion commit해주실 수 있나요~!

2021-03-02 09:09 UTC, gvsteve24 approved these changes

2021-03-02 09:11 UTC, merged